### ISSUE TITLE
Upgrade to Dioxus 0.5

### ISSUE THREAD

**Issue by anna-ahmed19** [mrxiaozhuox/dioxus-toast#4]
- Upgrade Dioxus library to 0.5
- Replace Fermi crate with Dioxus signals
- Upgrade other crates to latest versions

**Comment by anna-ahmed19** [comment]
Hey, @mrxiaozhuox 

I have addressed this issue and created a [Pull Request#5](https://github.com/mrxiaozhuox/dioxus-toast/pull/5).
Please review the changes and provide any feedback or suggestions.

Thank you.

**Comment by mrxiaozhuox** [comment]
> Hey, @mrxiaozhuox
> 
> I have addressed this issue and created a [Pull Request#5](https://github.com/mrxiaozhuox/dioxus-toast/pull/5). Please review the changes and provide any feedback or suggestions.
> 
> Thank you.

I will check it this week, thank you.

**Comment by mrxiaozhuox** [comment]
done by #5
